# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kestrel < Formula
  desc "Kestrel CLI — manage workflows from the terminal"
  homepage "https://usekestrel.ai"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KestrelAI/kestrel-cli/releases/download/v0.2.0/kestrel_darwin_amd64.tar.gz"
      sha256 "e65a5e0e82d073a6507717e5ee499bece0bd99ed24fac422d5222fa490f60014"

      define_method(:install) do
        bin.install "kestrel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KestrelAI/kestrel-cli/releases/download/v0.2.0/kestrel_darwin_arm64.tar.gz"
      sha256 "a6493201b22c9c38afe9af0bb178053d3727f3333c80b4b8928070cba0da4ce3"

      define_method(:install) do
        bin.install "kestrel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KestrelAI/kestrel-cli/releases/download/v0.2.0/kestrel_linux_amd64.tar.gz"
      sha256 "819bb4bcd2d8c7fd3640744e12adf0bb68163c6aab15c90dacdf0423b5a84bed"
      define_method(:install) do
        bin.install "kestrel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KestrelAI/kestrel-cli/releases/download/v0.2.0/kestrel_linux_arm64.tar.gz"
      sha256 "027e7137eb080243dfbd88be6d4c5976c2d3245e7e74deebf2553f61a9479006"
      define_method(:install) do
        bin.install "kestrel"
      end
    end
  end
end
