# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kestrel < Formula
  desc "Kestrel CLI — manage workflows from the terminal"
  homepage "https://usekestrel.ai"
  version "0.24.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KestrelAI/kestrel-cli/releases/download/v0.24.0/kestrel_darwin_amd64.tar.gz"
      sha256 "410e0b1b5852d1c534cb2348fb2ea55e058337822e7a136cd272eed3056adee3"

      define_method(:install) do
        bin.install "kestrel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KestrelAI/kestrel-cli/releases/download/v0.24.0/kestrel_darwin_arm64.tar.gz"
      sha256 "45692834b440c3a4163c2cab28cebc204bdd6cc2041d5bdd7f603299171a36a3"

      define_method(:install) do
        bin.install "kestrel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KestrelAI/kestrel-cli/releases/download/v0.24.0/kestrel_linux_amd64.tar.gz"
      sha256 "87a78305857a8ae62dc9b0dcc8918bf0411f2b2f9222f4a690d30fa1cc188cdd"
      define_method(:install) do
        bin.install "kestrel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KestrelAI/kestrel-cli/releases/download/v0.24.0/kestrel_linux_arm64.tar.gz"
      sha256 "98def193f56826795f68d64133afb0a1060f57e73acf28a2e3114f4dbf309059"
      define_method(:install) do
        bin.install "kestrel"
      end
    end
  end
end
